name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${PASSWORD}" #will be masked
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" #will be not masked
